### ISSUE TITLE
PKGBUILD editing

### ISSUE THREAD

**Issue by EveKaczmarek** [aji-prod/tomato#1]
It would be nice if tomato would support editing PKGBUILD files.

**Comment by aji-prod** [comment]
There are two showstopper:
 1. The *docker* base image doesn't have any editor,
 2. The *tomato* code forces the *pacman*'s `--noconfirm` flag, which prevents the `--edit` flag.

The *PKGBUILD*s should be editable with the `--edit` flag.
I will look into it.

**Comment by aji-prod** [comment]
Hi,

The `--edit` flag has been added and released in the latest *tomato v0.4.0*.
You can now edit the *PKGBUILD*s by passing this flag with the `tomato refresh` or `tomato add` commands.

Note that the default editor is fetched from your `$EDITOR` environment variable, but may not be appropriate, or installable, within the *Docker* image. In such case you can specify the editor command with the `TOMATO_EDITOR=` configuration key in the `tomato.conf` file.

The `TOMATO_EDITOR=` has a special syntax, as `TOMATO_EDITOR=package-name:command` (e.g. `TOMATO_EDITOR=extra/vim:/usr/bin/vim`).

If no `TOMATO_EDITOR=` nor the `$EDITOR` is defined, the editor will be *vim*.
