### ISSUE TITLE
archlinux/base does not exists anymore

### ISSUE THREAD

**Issue by bitwave** [aji-prod/tomato#2]
The `archlinux/base` image has been renamed to `archlinux`.

**Comment by aji-prod** [comment]
Hi,

Good catch.
As noted by the [Arch Linux download page](https://archlinux.org/download/), the official image is now [`archlinux`](https://hub.docker.com/_/archlinux/) as a *Docker Offical Image*.

I will look into it.

**Comment by aji-prod** [comment]
Hi,

The release v0.7.0 (9c1df3f) is now based on the [archlinux](https://hub.docker.com/_/archlinux/) docker image.
